steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker pull europe-west2-docker.pkg.dev/$PROJECT_ID/paymentsense/paymentsense:latest || exit 0']

  - name: 'gcr.io/cloud-builders/docker'
    args: [
            'build',
            '-t', 'europe-west2-docker.pkg.dev/$PROJECT_ID/paymentsense/paymentsense:latest',
            '--cache-from', 'europe-west2-docker.pkg.dev/$PROJECT_ID/paymentsense/paymentsense:latest',
            './application'
          ]

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: [ '-c', 'docker tag europe-west2-docker.pkg.dev/$PROJECT_ID/paymentsense/paymentsense:latest europe-west2-docker.pkg.dev/$PROJECT_ID/paymentsense/paymentsense:$SHORT_SHA' ]
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west2-docker.pkg.dev/$PROJECT_ID/paymentsense/paymentsense:latest']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'europe-west2-docker.pkg.dev/$PROJECT_ID/paymentsense/paymentsense:$SHORT_SHA']

  - name: 'gcr.io/cloud-builders/kubectl'
    args: [ 'cluster-info' ]
    env:
      - 'CLOUDSDK_COMPUTE_REGION=$_CUSTOM_REGION'
      - 'CLOUDSDK_CONTAINER_CLUSTER=$_CUSTOM_CLUSTER'
      - 'KUBECONFIG=/workspace/.kube/config'

  - name: 'alpine/helm:3.5.0'
    args: [ 'upgrade', '--install', 'paymentsense', './helm', '--set', 'image.url=europe-west2-docker.pkg.dev/refined-stream-190917/paymentsense/paymentsense,image.tag=$SHORT_SHA', '-f', './helm/values.yaml' ]
    env:
      - 'KUBECONFIG=/workspace/.kube/config'
      - 'TILLERLESS=true'
      - 'TILLER_NAMESPACE=default'
timeout: 1200s
substitutions:
  _CUSTOM_REGION: us-central1-a
  _CUSTOM_CLUSTER: nginx-1-cluster