apiVersion: v1
kind: Service
metadata:
  name: {{ template "paymentsense.name" . }}-service
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  selector:
    app: {{ template "paymentsense.name" . }}
    release: {{ .Release.Name }}